CREATE TABLE booking (
    b_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    b_p_id BIGINT NOT NULL,
    b_start_date DATE NOT NULL,
    b_end_date DATE NOT NULL,
    b_duration INT NOT NULL,
    b_stato ENUM('BOOKED', 'CANCELLED', 'COMPLETED') DEFAULT 'BOOKED',
    b_status BOOLEAN DEFAULT TRUE,
    b_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    b_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (b_p_id) REFERENCES property(p_id) ON DELETE CASCADE
);
